version: '3'
services:
  python-server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: grpc/python-server
    ports:
      - "9090:9090"
  envoy:
    build:
      context: ./envoy
      dockerfile: ./Dockerfile
    image: grpc/envoy
    ports:
      - "8080:8080"
    links:
      - python-server