version: '3'
services:
  common:
    build:
      context: ./common
      dockerfile: ./Dockerfile
    image: grpc/common
  python-server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: grpc/python-server
    ports:
      - "9090:9090"
  envoy:
    build:
      context: ./envoy
      dockerfile: ./Dockerfile
    image: grpc/envoy
    ports:
      - "8080:8080"
    links:
      - python-server
  js-client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    depends_on:
      - common
    image: grpc/js-client
    ports:
      - "8081:8081"
