# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ugh.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ugh.proto',
  package='ugh',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tugh.proto\x12\x03ugh\"\x07\n\x05\x45mpty\"*\n\x05Issue\x12\x10\n\x08issue_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t21\n\x03Ugh\x12*\n\x0cGetAllIssues\x12\n.ugh.Empty\x1a\n.ugh.Issue\"\x00\x30\x01\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='ugh.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=25,
)


_ISSUE = _descriptor.Descriptor(
  name='Issue',
  full_name='ugh.Issue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='issue_id', full_name='ugh.Issue.issue_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='ugh.Issue.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Issue'] = _ISSUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'ugh_pb2'
  # @@protoc_insertion_point(class_scope:ugh.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Issue = _reflection.GeneratedProtocolMessageType('Issue', (_message.Message,), dict(
  DESCRIPTOR = _ISSUE,
  __module__ = 'ugh_pb2'
  # @@protoc_insertion_point(class_scope:ugh.Issue)
  ))
_sym_db.RegisterMessage(Issue)



_UGH = _descriptor.ServiceDescriptor(
  name='Ugh',
  full_name='ugh.Ugh',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=71,
  serialized_end=120,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllIssues',
    full_name='ugh.Ugh.GetAllIssues',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ISSUE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UGH)

DESCRIPTOR.services_by_name['Ugh'] = _UGH

# @@protoc_insertion_point(module_scope)
